jhipster-dev-postgresql:
  container_name: gezondheid-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  # - ~/volumes/jhipster/gezondheid/dev-postgresql/:/var/lib/postgresql/
  environment:
  - POSTGRES_USER=gezondheid
  - POSTGRES_PASSWORD=
  ports:
  - "5432:5432"

